// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOMbzA7Hg8Vz20ZXy1GFbqMOov1ck4VUg',
    appId: '1:559036700260:web:09e18337b47a1e3925f171',
    messagingSenderId: '559036700260',
    projectId: 'flutter-lab1-42967',
    authDomain: 'flutter-lab1-42967.firebaseapp.com',
    storageBucket: 'flutter-lab1-42967.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3hsmDswIWfC1RUfuiN6wEGkQctaFedx0',
    appId: '1:559036700260:android:c5fef18b039239bd25f171',
    messagingSenderId: '559036700260',
    projectId: 'flutter-lab1-42967',
    storageBucket: 'flutter-lab1-42967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv3ilXgXABLSmGMIzqXDaUFvnN37892Q8',
    appId: '1:559036700260:ios:356769357513a63625f171',
    messagingSenderId: '559036700260',
    projectId: 'flutter-lab1-42967',
    storageBucket: 'flutter-lab1-42967.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

}